# Deployment config for Google App Engine

runtime: python312

instance_class: F1 # cheapest instance; optional

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  APP_ENVIRONMENT: 'production'

entrypoint: gunicorn -b :$PORT app:app
